import { Space_Grotesk, Syne } from "next/font/google";
import "./globals.css";


const spaceGrotesk = Space_Grotesk({
  variable: "--space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", '300'],
  display: "swap",
});

const syne = Syne({
  variable: "--syne",
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${syne.variable} antialiased `}
      >
      {/* <nav className="mx-auto w-[90vw] max-w-[1400px] h-15 bg-amber-200">this is nav</nav> */}
        {children}
      </body>
    </html>
  );
}
